apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-html
  labels:
    app: example-html
spec:
  selector:
    matchLabels:
      app: example-html
  template:
    metadata:
      labels:
        app: example-html
    spec:
      containers:
      - name: example-html
        image: example-html-image
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: volume
          mountPath: /pvc/
      volumes: 
      - name: volume
        persistentVolumeClaim:
          claimName: test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  labels:
    app: test
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
