
config.define_string('env')
c = config.parse()
docker_build('example-html-image', '.', container_args=['--env', c.get('env', 'default-env')])
k8s_yaml('kubernetes.yaml')
k8s_resource('example-html', port_forwards=8000)
