k8s_yaml('kubernetes.yaml')
docker_build('example-html', '.')
k8s_resource('example-html', port_forwards=8000, resource_deps=['deploy'])

# Records the start time.
# When the contents of this directory change, example-html will automatically re-deploy.
local_resource(
  'deploy',
  'date +%s > start-time.txt',
  trigger_mode=TRIGGER_MODE_MANUAL)
